#!/bin/bash

# Subfinder + Assetfinder subdomain enumeration
subfinder -d $1 -silent  -o $1_subfinder.txt
echo [+] Finished with Subfinder
amass enum -brute -w $2 -d $1 -silent -o $1_amass.txt
echo [+] Finished with Amass
echo $1 | assetfinder --subs-only > $1_assetfinder.txt
echo [+] Finished with Assetfinder
cat $1_subfinder.txt $1_assetfinder.txt $1_amass.txt | sort | uniq | tee $1_subdomains.txt
rm $1_subfinder.txt $1_assetfinder.txt $1_amass.txt
# Httpx host enumeration
httpx -l $1_subdomains.txt -silent -o $1_hosts.txt
echo [+] Finished with HTTPX
# aquatone flyover
mkdir aquatone
cat $1_hosts.txt | aquatone -silent -ports xlarge -out aquatone
echo [+] Finished with Aquatone. Happy Hunting!
